/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-18 05:57:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class enroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1657863477099L));
    _jspx_dependants.put("jar:file:/C:/Users/parkng/Desktop/develop/backend/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/05_MVC2/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header.jsp", out, false);
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("	section #enroll-container {\n");
      out.write("		text-align:center;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	section #enroll-container input {\n");
      out.write("		margin:3px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	section #enroll-container table {\n");
      out.write("		margin:0 auto;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	section #enroll-container table th {\n");
      out.write("		padding:0 10px; \n");
      out.write("		text-align:right;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	section #enroll-container table td {\n");
      out.write("		padding:0 10px; \n");
      out.write("		text-align:left;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<section id=\"content\">\n");
      out.write("	<h2 align=\"center\">회원 가입 정보</h2>\n");
      out.write("	<div id=\"enroll-container\">	 	\n");
      out.write("	 	<form name=\"memberEnrollFrm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/enroll\" method=\"post\">\n");
      out.write("	 		<table>\n");
      out.write("	 			<tr>\n");
      out.write("					<th>아이디</th>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"text\" name=\"userId\" id=\"newId\" placeholder=\"아이디(4글자이상)\" required>\n");
      out.write("						<input type=\"button\" id=\"checkDuplicate\" value=\"중복검사\" >\n");
      out.write("					</td> 			\n");
      out.write("	 			</tr>\n");
      out.write("	 			<tr>\n");
      out.write("					<th>패스워드</th>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"password\" name=\"userPwd\" id=\"pass1\" required>\n");
      out.write("					</td> 			\n");
      out.write("	 			</tr>\n");
      out.write("	 			<tr>\n");
      out.write("					<th>패스워드확인</th>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"password\" id=\"pass2\">\n");
      out.write("					</td> 			\n");
      out.write("	 			</tr>\n");
      out.write("	 			<tr>\n");
      out.write("					<th>이름</th>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"text\" name=\"userName\" id=\"userName\" required>				\n");
      out.write("					</td> 			\n");
      out.write("	 			</tr>\n");
      out.write("	 			<tr>\n");
      out.write("					<th>휴대폰</th>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"tel\" placeholder=\"(-없이)01012345678\" name=\"phone\" id=\"phone\" maxlength=\"11\">								\n");
      out.write("					</td> 			\n");
      out.write("	 			</tr>\n");
      out.write("	 			<tr>\n");
      out.write("					<th>이메일</th>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"email\" placeholder=\"abc@abc.com\" name=\"email\" id=\"email\">												\n");
      out.write("					</td> 			\n");
      out.write("	 			</tr>\n");
      out.write("	 			<tr>\n");
      out.write("					<th>주소</th>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"text\" name=\"address\" id=\"address\">\n");
      out.write("					</td> 			\n");
      out.write("	 			</tr>\n");
      out.write("	 			<tr>\n");
      out.write("					<th>취미</th>\n");
      out.write("					<td>\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" id=\"hobby0\" value=\"운동\">운동</label>\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" id=\"hobby1\" value=\"등산\">등산</label>\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" id=\"hobby2\" value=\"독서\">독서</label>\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" id=\"hobby3\" value=\"게임\">게임</label>\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" id=\"hobby4\" value=\"여행\">여행</label>\n");
      out.write("					</td> 			\n");
      out.write("	 			</tr> 		\n");
      out.write("	 		</table> \n");
      out.write("	 		<input type=\"submit\" id=\"enrollSubmit\" value=\"가입\">	\n");
      out.write("	 		<input type=\"reset\" value=\"취소\">	\n");
      out.write("	 	</form>\n");
      out.write("	 	<form name=\"checkIdForm\">\n");
      out.write("	 		<input type=\"hidden\" name=\"userId\">\n");
      out.write("	 	</form>\n");
      out.write(" 	</div>\n");
      out.write("</section>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/footer.jsp", out, false);
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /views/member/enroll.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /views/member/enroll.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/views/member/enroll.jsp(5,0) '${ pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
